### ISSUE TITLE
Parameter expand is treated like concat operator

### ISSUE THREAD

**Issue by egils** [InterNations/kodierungsregelwerksammlung#11]
PHP 5.6 parameter expand operator "..." is treated like Concat operator "." and produces a warning. 
Example line of code:
```
$this->functionCall($key, ...$additionalParameters);
```
Warning:
```
Concat operator must be surrounded by exactly one space
```

**Comment by dovys** [comment]
Are you sure you're running it with php 5.6? I've been getting this error while running phpcs with 5.4, but not 5.6.

**Comment by egils** [comment]
You are right. This looks weird on PhpStorm that interpreter is configured to be PHP 5.6 on VM but for phpcs inspections it uses local machine's php (which was php 5.5). Closing it now.
